### ISSUE TITLE
iPad icons?

### ISSUE THREAD

**Issue by annca** [Nonchalant/AppIcon#22]
Great util! Wondering if it would be possible to add the option for iPad icon size as well?

**Comment by Nonchalant** [comment]
@annca 
Thank you for reporting issue ✨
I enable to generate iPad icon from next version 🚀 

Just a moment, please 🙇‍♀️

**Comment by Nonchalant** [comment]
@annca 
Just released [ver.0.3.0](https://github.com/Nonchalant/AppIcon/releases/tag/0.3.0) 🎉 
This version enable to generate iPad icon 🚀 
Please try when you have time 👍 

https://github.com/Nonchalant/AppIcon/releases/tag/0.3.0

**Comment by annca** [comment]
Awesome. Thanks for such a quick update!! 😃
