### ISSUE TITLE
Missing Sizes

### ISSUE THREAD

**Issue by mzgnr** [Nonchalant/AppIcon#26]
![screen shot 2017-07-05 at 14 34 27](https://user-images.githubusercontent.com/6003317/27862679-1f9680ae-618f-11e7-9b15-a7f361539f43.png)

**Comment by Nonchalant** [comment]
@mzgnr 
Thank you for reporting issue 💡 

Please show me command when occured this warning 🙇‍♀️

**Comment by mzgnr** [comment]
my bad 😢
