### ISSUE TITLE
Can support macapp icons?

### ISSUE THREAD

**Issue by madordie** [Nonchalant/AppIcon#27]
Can support macapp icons?

**Comment by Nonchalant** [comment]
@madordie
Thank you for reporting issue ✨
I enable to generate mac application icon from next version 🚀

Just a moment, please 🙇‍♀️

**Comment by Nonchalant** [comment]
@madordie
Just released ver.0.3.1 🎉
This version enable to generate Mac icon 🚀
Please try when you have time 👍

https://github.com/Nonchalant/AppIcon/releases/tag/0.3.1

**Comment by gingerbeardman** [comment]
Unlike iOS, macOS icon require to be made with squircle and shadow. https://github.com/Nonchalant/AppIcon/issues/84
