### ISSUE TITLE
got errors on uploading my app to apple store.

### ISSUE THREAD

**Issue by ymmtshny** [Nonchalant/AppIcon#39]
AppIcon is a great utility!! 

However, I got errors of appIcon when I uploaded my app to Apple Store.

![2018-03-11 16 04 57](https://user-images.githubusercontent.com/16192521/37250753-6f2b0844-2546-11e8-8ed3-9d92b743a2b4.png)

Basically, it tells us that some sizes are missing and the icons should be jpg instead of png.

Thanks :)

**Comment by Nonchalant** [comment]
@ymmtshny 
Thank you for reporting issues 🙇‍♀️ 
I think there are two problems 🤔 

## 1. Missing size

Maybe, your appicon version is old. Please upgrade latest one! 🚀 

## 2. Alpha channel

Your app base image contains alpha channel. After your remove, please retry! 🚀 
ref: https://stackoverflow.com/questions/46585809/error-itms-90717-invalid-app-store-icon

**Comment by ymmtshny** [comment]
@Nonchalant 
Thanks for your reply. 
I'll update AppIcon next time 👍 
As for Alpha Channel, if AppIcon automatically removes alpha channel from the base image, it is going to be great.
