### ISSUE TITLE
Generate icons for iPad and update Contents.json accordingly for Xcode? 

### ISSUE THREAD

**Issue by ankushkushwaha** [Nonchalant/AppIcon#40]
Hi,

Thanks for this nice tool. It is working very well, it would be nice if the software can also generate the icons for iPad as well for universal iOS application

**Comment by Nonchalant** [comment]
@ankushkushwaha 
Did you try below commands ?
`appicon iTunesIcon-1024x1024.png --ipad`

**Comment by ankushkushwaha** [comment]
Oh! Okay, My mistake. I did not read the documentation carefully. Yes it is working for iPad as well
