### ISSUE TITLE
generated a wrong name file

### ISSUE THREAD

**Issue by SuperDannyBoy** [Nonchalant/AppIcon#41]
when i use 'appicon Text.png --ipad'
finally it generated two same suffix file
`appicon Text.png --ipad
{AppIcon}.appiconset.appiconset is generated 🎉`

**Comment by Nonchalant** [comment]
@SuperDannyBoy 
Thank you for reporting. ✨ 

I tried `appicon Text.png --ipad`, its output is `AppIcon.appiconset.appiconset is generated 🎉`.
I want to know your appicon version. Please try below command.

```
$ ls /usr/local/Cellar/appicon
```

**Comment by Nonchalant** [comment]
@SuperDannyBoy 
Did you install by homebrew or Manual?

**Comment by SuperDannyBoy** [comment]
@Nonchalant 
Clone the master branch of the repository, then run make install.

**Comment by Nonchalant** [comment]
@SuperDannyBoy 
Thank you! ✨ 
Please try update and show version!

```shell
$ git pull origin master
$ make install
```

```shell
$ appicon --version
```

**Comment by SuperDannyBoy** [comment]
@Nonchalant 
`$ appicon --version`
`$ 1.0.0`

**Comment by Nonchalant** [comment]
@SuperDannyBoy 
I'm glad!! Thank you for reporting!!
