### ISSUE TITLE
can't generate all icons after resizing with imagemagick's point filter?

### ISSUE THREAD

**Issue by slmjkdbtl** [Nonchalant/AppIcon#47]
after running `convert icon.png -filter point -resize 1024x1024 icon.png`, the generated `AppIcon.appiconset` only contains a `AppIcon-1024.0x1024.0@1x.png` and a `Contents.json`

the program works perfectly fine if resize with no filter, or is it an imgemagick's issue

edit 2018.07.15:
and sometimes it also works, weird

**Comment by Nonchalant** [comment]
@Camji55 thank you for your nice work!!
