### ISSUE TITLE
WatchOS assets

### ISSUE THREAD

**Issue by JMCPH** [Nonchalant/AppIcon#64]
Would you guys be accepting a PR, which included a --watchOS feature? I'm planning to develop that over the weekend 👍

**Comment by Nonchalant** [comment]
That's good. Looking forward to seeing your PR!

**Comment by JMCPH** [comment]
@Nonchalant I have made a PR. Please look through it and let me know what you think.

**Comment by JMCPH** [comment]
Merged in.
