### ISSUE TITLE
[Homebrew] Warning when using AppIcon via brew

### ISSUE THREAD

**Issue by bennokress** [Nonchalant/AppIcon#76]
When intalling and upgrading packages via `brew` while AppIcon is also installed with Homebrew, I get the following warning for a while now:

> Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the nonchalant/appicon tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/nonchalant/homebrew-appicon/appicon.rb:13

I'm not sure if this is an easy fix, but I wanted to let you know about it.

**Comment by chellem** [comment]
Hello, am having the same issue as @bennokress .

Please fix it.  It seems to be a very nice tools to have.

**Comment by chocoford-zhang** [comment]
+1
But instead, I got `Error: Cannot tap nonchalant/appicon: invalid syntax in tap!` due to the same error

**Comment by Nonchalant** [comment]
Thank you for your reports.
@himbeles fixed this issue.
https://github.com/Nonchalant/homebrew-appicon/pull/3

**Comment by chellem** [comment]
Hello @Nonchalant,

Yes, it's now working and very useful <3
